### PR TITLE
Create top 7 things to ask or look for when hiring sw developers

### PR DESCRIPTION
**Pull request by junezzz**
top 7 things to ask or look for when hiring sw developers at startups

### CODE REVIEW

**Comment by junezzz** [comment]
@rog97 @Rbhojania 
Can you guys take a look at my work and provide some feedback? Thanks!

**Comment by roger-teran** [comment]
Hey @junezzz I think you should add:

+Being able to explain complex topics and concepts as if I'm a 10-year-old.

**Comment by Rbhojania** [comment]
@junezzz this looks great. Should a question about a developer's work on open source software also be one of the top 7?

**Comment by roger-teran** [comment]
:+1:

**Comment by roger-teran** [comment]
octocat

**Pull request merged**
