### PR TITLE
Rbhojania   top tips for specifying software

### PR DESCRIPTION
**Pull request by Rbhojania**
Hey @rog97 @junezzz ! Any comments on my section on specifying software?

### CODE REVIEW

**Comment by roger-teran** [comment]
Hey @Rbhojania I think you should briefly mention that hourly is better than fix bid

**Comment by junezzz** [comment]
:+1:

**Comment by junezzz** [comment]
happy dance

**Comment by roger-teran** [comment]
:+1:

**Comment by Rbhojania** [comment]
Thanks guys! Merging now

**Pull request merged**
